import { SitePageHeader } from '~/(marketing)/_components/site-page-header';
import { createI18nServerInstance } from '~/lib/i18n/i18n.server';
import { withI18n } from '~/lib/i18n/with-i18n';

export async function generateMetadata() {
  const { t } = await createI18nServerInstance();

  return {
    title: t('marketing:termsOfService'),
  };
}

async function TermsOfServicePage() {
  const { t } = await createI18nServerInstance();

  return (
    <div>
      <SitePageHeader
        title={t(`marketing:termsOfService`)}
        subtitle={t(`marketing:termsOfServiceDescription`)}
      />

      <div className="container mx-auto max-w-3xl px-4 py-12">
        <div className="prose prose-zinc dark:prose-invert max-w-none">
          <p className="text-muted-foreground text-sm">
            Last updated: January 9, 2025
          </p>

          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using Sparlo (&quot;Service&quot;), you agree to
              be bound by these Terms of Service (&quot;Terms&quot;). If you do
              not agree to these Terms, you may not access or use the Service.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              Sparlo is an AI-powered engineering intelligence platform that
              provides technical analysis, solution generation, and research
              assistance for R&D teams. The Service processes user-submitted
              technical queries and generates analytical reports and potential
              solutions.
            </p>
          </Section>

          <Section title="3. User Accounts">
            <p>
              To access certain features of the Service, you must create an
              account. You are responsible for:
            </p>
            <ul>
              <li>
                Maintaining the confidentiality of your account credentials.
              </li>
              <li>All activities that occur under your account.</li>
              <li>Notifying us immediately of any unauthorized use.</li>
            </ul>
            <p>
              You may not share your account credentials with any third party.
            </p>
          </Section>

          <Section title="4. Intellectual Property Rights">
            <h4>Your Content</h4>
            <p>
              You retain all intellectual property rights to the content,
              research data, technical specifications, and other materials you
              submit to the Service (&quot;Your Content&quot;). Sparlo does not
              claim any ownership rights in Your Content.
            </p>

            <h4>Generated Output</h4>
            <p>
              Subject to these Terms, you own all rights to the solutions,
              analyses, reports, and other content generated by the Service
              based on Your Content (&quot;Output&quot;). You may use, modify,
              reproduce, distribute, and create derivative works from the Output
              for any lawful purpose, including commercial use.
            </p>

            <h4>Sparlo Property</h4>
            <p>
              The Service, including its underlying technology, AI models,
              algorithms, user interface, and platform infrastructure, is and
              remains the exclusive property of Sparlo. You are granted a
              limited, non-exclusive, non-transferable, revocable license to use
              the Service in accordance with these Terms.
            </p>
          </Section>

          <Section title="5. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>
                Use the Service for any unlawful purpose or in violation of any
                applicable laws or regulations.
              </li>
              <li>
                Attempt to reverse engineer, decompile, disassemble, or extract
                the source code of our AI models or other proprietary
                technology.
              </li>
              <li>
                Use the Service to develop competing products or services.
              </li>
              <li>
                Share, transfer, or sublicense your account credentials to any
                third party.
              </li>
              <li>
                Submit content that infringes upon the intellectual property
                rights of any third party.
              </li>
              <li>
                Interfere with, disrupt, or attempt to gain unauthorized access
                to the Service or its related systems.
              </li>
              <li>
                Use automated means to access the Service except through
                authorized APIs.
              </li>
            </ul>
          </Section>

          <Section title="6. Payment and Subscription">
            <p>
              Certain features of the Service require a paid subscription.
              Payment terms, including pricing and billing cycles, are presented
              at the time of purchase. All fees are non-refundable except as
              expressly set forth herein or as required by applicable law.
            </p>
            <p>
              Subscriptions automatically renew at the end of each billing cycle
              unless cancelled prior to the renewal date. You may cancel your
              subscription at any time through your account settings.
            </p>
          </Section>

          <Section title="7. Disclaimer of Warranties">
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS
              AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
              IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
              MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
              NON-INFRINGEMENT.
            </p>
            <p>Sparlo does not warrant that:</p>
            <ul>
              <li>The Service will meet your specific requirements.</li>
              <li>
                The Output will be accurate, complete, reliable, or suitable for
                any particular purpose.
              </li>
              <li>
                The Service will be uninterrupted, timely, secure, or
                error-free.
              </li>
            </ul>
            <p>
              The Output is intended as a starting point for further research
              and development. You are solely responsible for validating,
              testing, and verifying any Output before relying on it for
              critical decisions, implementations, or commercial applications.
            </p>
          </Section>

          <Section title="8. Limitation of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
              SHALL SPARLO, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, OR
              AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO
              LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL,
              ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE
              SERVICE, REGARDLESS OF THE THEORY OF LIABILITY.
            </p>
            <p>
              IN NO EVENT SHALL SPARLO&apos;S TOTAL LIABILITY TO YOU FOR ALL
              CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE
              EXCEED THE AMOUNTS PAID BY YOU TO SPARLO DURING THE TWELVE (12)
              MONTHS PRECEDING THE CLAIM.
            </p>
          </Section>

          <Section title="9. Indemnification">
            <p>
              You agree to indemnify, defend, and hold harmless Sparlo, its
              affiliates, officers, directors, employees, and agents from and
              against any and all claims, damages, losses, liabilities, costs,
              and expenses (including reasonable attorneys&apos; fees) arising
              out of or related to: (a) your use of the Service; (b) Your
              Content; (c) your violation of these Terms; or (d) your violation
              of any rights of a third party.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              Sparlo may suspend or terminate your access to the Service at any
              time, with or without cause, and with or without notice, for
              violation of these Terms or for any other reason at our sole
              discretion. Upon termination, your right to use the Service ceases
              immediately.
            </p>
            <p>
              You may terminate your account at any time. Prior to termination,
              you may export your data using the data export features provided
              in the Service.
            </p>
            <p>
              Sections 4, 7, 8, 9, and 12 shall survive any termination of these
              Terms.
            </p>
          </Section>

          <Section title="11. Modifications to Terms">
            <p>
              Sparlo reserves the right to modify these Terms at any time. We
              will notify you of material changes by posting the updated Terms
              on our website and, where appropriate, by email notification. Your
              continued use of the Service following the posting of revised
              Terms constitutes your acceptance of such changes.
            </p>
          </Section>

          <Section title="12. Governing Law and Dispute Resolution">
            <p>
              These Terms shall be governed by and construed in accordance with
              the laws of the State of Delaware, United States, without regard
              to its conflict of law provisions. Any dispute arising out of or
              relating to these Terms or the Service shall be resolved
              exclusively in the state or federal courts located in Delaware,
              and you consent to the personal jurisdiction of such courts.
            </p>
          </Section>

          <Section title="13. General Provisions">
            <p>
              These Terms constitute the entire agreement between you and Sparlo
              regarding the Service and supersede all prior agreements and
              understandings. If any provision of these Terms is held to be
              invalid or unenforceable, such provision shall be struck and the
              remaining provisions shall remain in full force and effect.
              Sparlo&apos;s failure to enforce any right or provision of these
              Terms shall not constitute a waiver of such right or provision.
            </p>
          </Section>

          <Section title="14. Contact">
            <p>
              For questions regarding these Terms of Service, please contact us
              at{' '}
              <a href="mailto:legal@sparlo.ai" className="text-primary">
                legal@sparlo.ai
              </a>
              .
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8 first:mt-0">
      <h3 className="mb-4 text-xl font-semibold tracking-tight">{title}</h3>
      <div className="text-muted-foreground space-y-3 leading-relaxed">
        {children}
      </div>
    </section>
  );
}

export default withI18n(TermsOfServicePage);
