import { SitePageHeader } from '~/(marketing)/_components/site-page-header';
import { createI18nServerInstance } from '~/lib/i18n/i18n.server';
import { withI18n } from '~/lib/i18n/with-i18n';

export async function generateMetadata() {
  const { t } = await createI18nServerInstance();

  return {
    title: t('marketing:termsOfService'),
  };
}

async function TermsOfServicePage() {
  const { t } = await createI18nServerInstance();

  return (
    <div>
      <SitePageHeader
        title={t(`marketing:termsOfService`)}
        subtitle={t(`marketing:termsOfServiceDescription`)}
      />

      <div className="container mx-auto max-w-3xl px-4 py-12">
        <div className="prose prose-zinc dark:prose-invert max-w-none">
          <p className="text-muted-foreground text-sm">
            Last updated: January 2, 2025
          </p>

          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using Sparlo (&quot;Service&quot;), you agree to
              be bound by these Terms of Service. If you do not agree to these
              terms, please do not use our Service.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              Sparlo is an AI-powered engineering intelligence platform that
              helps R&D teams generate innovative solutions to complex technical
              challenges. The Service provides technical analysis, solution
              generation, and research assistance.
            </p>
          </Section>

          <Section title="3. User Accounts">
            <p>
              To access certain features of the Service, you must create an
              account. You are responsible for:
            </p>
            <ul>
              <li>
                Maintaining the confidentiality of your account credentials
              </li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>
          </Section>

          <Section title="4. Intellectual Property Rights">
            <h4>Your Content and IP</h4>
            <p>
              You retain all intellectual property rights to the content,
              research data, technical specifications, and other materials you
              submit to the Service (&quot;Your Content&quot;). We do not claim
              ownership of Your Content.
            </p>

            <h4>Generated Output</h4>
            <p>
              Any solutions, analyses, or content generated by the Service based
              on Your Content (&quot;Output&quot;) are provided for your use.
              You may use, modify, and incorporate the Output into your projects
              and intellectual property.
            </p>

            <h4>Our Service</h4>
            <p>
              Sparlo and its underlying technology, including our AI models,
              algorithms, and platform infrastructure, remain our exclusive
              property. You are granted a limited, non-exclusive license to use
              the Service in accordance with these terms.
            </p>
          </Section>

          <Section title="5. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>
                Use the Service for any unlawful purpose or in violation of any
                applicable laws
              </li>
              <li>
                Attempt to reverse engineer, decompile, or extract the source
                code of our AI models
              </li>
              <li>Use the Service to develop competing products or services</li>
              <li>Share account credentials with unauthorized parties</li>
              <li>
                Submit content that infringes on third-party intellectual
                property rights
              </li>
              <li>
                Interfere with or disrupt the integrity or performance of the
                Service
              </li>
            </ul>
          </Section>

          <Section title="6. Payment and Subscription">
            <p>
              Certain features of the Service require a paid subscription.
              Payment terms, including pricing and billing cycles, are presented
              at the time of purchase. Subscriptions automatically renew unless
              cancelled before the renewal date.
            </p>
          </Section>

          <Section title="7. Disclaimer of Warranties">
            <p>
              The Service is provided &quot;as is&quot; and &quot;as
              available&quot; without warranties of any kind, either express or
              implied. We do not warrant that:
            </p>
            <ul>
              <li>The Service will meet your specific requirements</li>
              <li>
                The Output will be error-free, complete, or suitable for any
                particular purpose
              </li>
              <li>The Service will be uninterrupted or secure</li>
            </ul>
            <p>
              The Output is intended as a starting point for further research
              and development. You are responsible for validating, testing, and
              verifying any Output before relying on it for critical decisions
              or implementations.
            </p>
          </Section>

          <Section title="8. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, Sparlo and its affiliates
              shall not be liable for any indirect, incidental, special,
              consequential, or punitive damages, including but not limited to
              loss of profits, data, or business opportunities, arising out of
              or related to your use of the Service.
            </p>
          </Section>

          <Section title="9. Indemnification">
            <p>
              You agree to indemnify and hold harmless Sparlo, its officers,
              directors, employees, and agents from any claims, damages, losses,
              or expenses arising out of your use of the Service or violation of
              these terms.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              We may suspend or terminate your access to the Service at any time
              for violation of these terms or for any other reason at our
              discretion. Upon termination, your right to use the Service ceases
              immediately. You may export your data before termination using our
              data export features.
            </p>
          </Section>

          <Section title="11. Changes to Terms">
            <p>
              We may modify these terms at any time. We will notify you of
              material changes by posting the updated terms on our website or
              sending you an email. Your continued use of the Service after such
              changes constitutes acceptance of the new terms.
            </p>
          </Section>

          <Section title="12. Governing Law">
            <p>
              These terms shall be governed by and construed in accordance with
              the laws of the State of Delaware, United States, without regard
              to its conflict of law provisions.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              For questions about these Terms of Service, please contact us at{' '}
              <a href="mailto:legal@sparlo.ai" className="text-primary">
                legal@sparlo.ai
              </a>
              .
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8 first:mt-0">
      <h3 className="mb-4 text-xl font-semibold tracking-tight">{title}</h3>
      <div className="text-muted-foreground space-y-3 leading-relaxed">
        {children}
      </div>
    </section>
  );
}

export default withI18n(TermsOfServicePage);
