import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

import type { ReportForPDF } from '../_lib/types';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 20,
    marginBottom: 8,
    fontFamily: 'Helvetica-Bold',
  },
  headline: {
    fontSize: 12,
    color: '#666666',
    marginBottom: 20,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 8,
    color: '#1a1a1a',
  },
  content: {
    lineHeight: 1.5,
    color: '#333333',
  },
  listItem: {
    marginBottom: 6,
    paddingLeft: 10,
  },
  stepNumber: {
    fontFamily: 'Helvetica-Bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#999999',
  },
});

interface Props {
  report: ReportForPDF;
}

export function ReportPDFDocument({ report }: Props) {
  const data = report.report_data;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{report.title}</Text>

        {report.headline && (
          <Text style={styles.headline}>{report.headline}</Text>
        )}

        {data?.executive_summary?.core_insight && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Executive Summary</Text>
            <Text style={styles.content}>
              {data.executive_summary.core_insight.headline}
            </Text>
            <Text style={[styles.content, { marginTop: 8 }]}>
              {data.executive_summary.core_insight.explanation}
            </Text>
          </View>
        )}

        {data?.problem_analysis?.whats_wrong && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Problem Analysis</Text>
            <Text style={styles.content}>
              {data.problem_analysis.whats_wrong.prose}
            </Text>
          </View>
        )}

        {data?.solution_concepts?.lead_concepts &&
          data.solution_concepts.lead_concepts.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Recommended Solutions</Text>
              {data.solution_concepts.lead_concepts.map((concept, i) => (
                <View key={concept.id} style={styles.listItem}>
                  <Text style={styles.content}>
                    <Text style={styles.stepNumber}>{i + 1}. </Text>
                    {concept.title}
                    {concept.bottom_line && ` - ${concept.bottom_line}`}
                  </Text>
                </View>
              ))}
            </View>
          )}

        {data?.next_steps?.steps && data.next_steps.steps.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Next Steps</Text>
            {data.next_steps.steps.map((step) => (
              <View key={step.step_number} style={styles.listItem}>
                <Text style={styles.content}>
                  <Text style={styles.stepNumber}>{step.step_number}. </Text>
                  {step.action}
                  {step.timeframe && ` (${step.timeframe})`}
                </Text>
                {step.details && (
                  <Text style={[styles.content, { marginTop: 2 }]}>
                    {step.details}
                  </Text>
                )}
              </View>
            ))}
          </View>
        )}

        {data?.risks_and_watchouts && data.risks_and_watchouts.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Risks & Watchouts</Text>
            {data.risks_and_watchouts.map((risk, i) => (
              <View key={i} style={styles.listItem}>
                <Text style={styles.content}>
                  <Text style={styles.stepNumber}>{risk.name}: </Text>
                  {risk.description}
                </Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footer}>
          Generated by Sparlo |{' '}
          {new Date(report.created_at).toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}
